--Truncate de las tablas de roles y usuarios
TRUNCATE TBL_ROLES;
TRUNCATE TBL_USERS;
TRUNCATE TBL_USERS_ROLES;

--Roles

INSERT INTO TBL_ROLES
	(ROLE_ID, NAME)
SELECT
	SQ_ROLES.NEXTVAL, B1.NAME
FROM 
	OFFER9_AMX_CENAM_HN_UAT.TBL_ROLES B1
WHERE
	B1.NAME NOT IN (SELECT B2.NAME FROM TBL_ROLES B2);

COMMIT;

--Usuarios Claro No Bloqueados
INSERT INTO TBL_USERS
	(USER_ID,USER_ACCOUNT,USER_PASSWORD,NAME,SURNAME,EMAIL,SPECIFIC_LANGUAGE_CODE,ALLOW_MULTI_SESSION,IS_BLOCKED,MUST_CHANGE_PASSWORD,INVALID_ATTEMPTS_NUMBER,LAST_PASSWORD_CHANGE,PARENT_USER_ID,DIGEST_HASH,SAP_USER_ACCOUNT)
SELECT
	SQ_USERS.NEXTVAL, B1.USER_ACCOUNT,B1.USER_PASSWORD,B1.NAME,B1.SURNAME,B1.EMAIL,B1.SPECIFIC_LANGUAGE_CODE,B1.ALLOW_MULTI_SESSION,B1.IS_BLOCKED,B1.MUST_CHANGE_PASSWORD,B1.INVALID_ATTEMPTS_NUMBER,B1.LAST_PASSWORD_CHANGE,B1.PARENT_USER_ID,B1.DIGEST_HASH,B1.SAP_USER_ACCOUNT
FROM 
	OFFER9_AMX_CENAM_HN_UAT.TBL_USERS B1
WHERE
	B1.USER_ACCOUNT NOT IN (SELECT B2.USER_ACCOUNT FROM TBL_USERS B2) 
	AND B1.IS_BLOCKED= 'N' AND B1.EMAIL LIKE '%@claro.com%';

COMMIT;

--Relacion Roles-Usuarios

INSERT INTO TBL_USERS_ROLES
	SELECT SQ_USERS_ROLES.NEXTVAL , B2.USER_ID, B3.ROLE_ID
	FROM OFFER9_AMX_CENAM_HN_UAT.TBL_USERS_ROLES B1
	INNER JOIN TBL_USERS B2 ON OFFER9_AMX_CENAM_HN_UAT.USER_ACCOUNT = B2.USER_ACCOUNT
	INNER JOIN TBL_ROLES B3 ON OFFER9_AMX_CENAM_HN_UAT.NAME = B3.NAME;
	
COMMIT;
